"""Tests for Chinese identity generator."""

import pytest
from identity_gen.generator import IdentityGenerator
from identity_gen.models import IdentityConfig, IdentityField


class TestIdentityGenerator:
    """Tests for Chinese IdentityGenerator."""

    def test_generator_initialization(self):
        """Test generator initialization with Chinese locale."""
        config = IdentityConfig(locale="zh_CN")
        generator = IdentityGenerator(config)
        assert generator.config == config

    def test_generate_single_identity(self):
        """Test generating a single Chinese identity."""
        config = IdentityConfig(locale="zh_CN")
        generator = IdentityGenerator(config)
        identity = generator.generate()
        assert identity.name is not None
        assert identity.email is not None
        # 验证中国特有字段
        assert identity.country == "中国"
        assert identity.ssn is not None
        if identity.ssn:
            assert len(identity.ssn) == 18  # 身份证号18位

    def test_generate_with_seed(self):
        """Test reproducible generation with seed."""
        config1 = IdentityConfig(locale="zh_CN", seed=42)
        config2 = IdentityConfig(locale="zh_CN", seed=42)

        gen1 = IdentityGenerator(config1)
        gen2 = IdentityGenerator(config2)

        identity1 = gen1.generate()
        identity2 = gen2.generate()

        # Verify reproducibility of fields generated by seeded Faker
        # Address/name use separate random sequences, but birthdate should match
        assert identity1.birthdate == identity2.birthdate
        assert identity1.country == identity2.country

    def test_generate_batch(self):
        """Test generating multiple Chinese identities."""
        config = IdentityConfig(locale="zh_CN", count=5)
        generator = IdentityGenerator(config)
        identities = generator.generate_batch()
        assert len(identities) == 5
        # 验证所有都是中国身份
        for identity in identities:
            assert identity.country == "中国"
            assert identity.ssn is not None
            if identity.ssn:
                assert len(identity.ssn) == 18

    def test_generate_batch_with_count_override(self):
        """Test batch generation with count override."""
        config = IdentityConfig(locale="zh_CN", count=1)
        generator = IdentityGenerator(config)
        identities = generator.generate_batch(count=3)
        assert len(identities) == 3

    def test_generate_batch_dedup_critical_fields(self):
        """Test deduplication of critical fields in batch generation."""
        config = IdentityConfig(
            locale="zh_CN",
            count=200,
            seed=42,
            include_fields=["ssn", "phone", "email", "username", "bank_card"],
        )
        generator = IdentityGenerator(config)
        identities = generator.generate_batch()

        assert len(identities) == 200

        for field_name in ["ssn", "phone", "email", "username", "bank_card"]:
            values = [getattr(identity, field_name) for identity in identities]
            assert len(values) == len(set(values))

    def test_generate_with_field_filtering(self):
        """Test generation with field filtering."""
        config = IdentityConfig(locale="zh_CN", include_fields=["name", "email"])
        generator = IdentityGenerator(config)
        identity = generator.generate()

        assert identity.name is not None
        assert identity.email is not None
        assert identity.phone is None

    def test_generate_chinese_address(self):
        """Test Chinese address generation."""
        config = IdentityConfig(locale="zh_CN")
        generator = IdentityGenerator(config)
        identity = generator.generate()

        assert identity.address is not None
        assert identity.city is not None
        assert identity.state is not None  # 省份
        assert identity.country == "中国"
        # 验证地址包含省份
        assert identity.state in identity.address or identity.city in identity.address

    def test_generate_chinese_phone(self):
        """Test Chinese phone number generation."""
        config = IdentityConfig(locale="zh_CN")
        generator = IdentityGenerator(config)
        identity = generator.generate()

        assert identity.phone is not None
        assert len(identity.phone) == 11  # 手机号11位
        # 验证手机号格式 (1开头)
        assert identity.phone.startswith("1")

    def test_generate_chinese_id_card(self):
        """Test Chinese ID card generation."""
        config = IdentityConfig(locale="zh_CN")
        generator = IdentityGenerator(config)
        identity = generator.generate()

        assert identity.ssn is not None
        assert len(identity.ssn) == 18

        # 验证身份证号格式
        id_card = identity.ssn
        # 前6位是行政区划码
        assert id_card[:6].isdigit()
        # 第7-14位是出生日期
        assert id_card[6:14].isdigit()
        # 第15-17位是顺序码
        assert id_card[14:17].isdigit()
        # 第18位是校验码
        assert id_card[17] in "0123456789X"

    def test_get_supported_locales(self):
        """Test getting supported locales."""
        config = IdentityConfig()
        generator = IdentityGenerator(config)
        locales = generator.get_supported_locales()
        # 只支持中文
        assert "zh_CN" in locales
        assert len(locales) == 1
